# Generated by Django 3.2.3 on 2021-05-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='short_url',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
