# Generated by Django 3.2.3 on 2021-05-20 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_form_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='formitem',
            name='field',
        ),
        migrations.AddField(
            model_name='formitem',
            name='field',
            field=models.ManyToManyField(to='main.Field'),
        ),
    ]
