# Generated by Django 3.2.3 on 2021-05-21 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210520_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='_id',
            new_name='ids',
        ),
        migrations.RenameField(
            model_name='field',
            old_name='_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='field',
            old_name='_required',
            new_name='required',
        ),
        migrations.RenameField(
            model_name='field',
            old_name='_type',
            new_name='types',
        ),
    ]
